[package]
name = "jim"
version = "0.1.0"
authors = ["Cameron Dart <cdart@anduril.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
git2 = "0.13"
prettytable-rs = "0.8"
termion = "1.5"
tui = "0.11"